# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Client_page(object):
    def setupUi(self, Client_page):
        Client_page.setObjectName("Client_page")
        Client_page.resize(911, 678)
        Client_page.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        Client_page.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.space = QtWidgets.QWidget(parent=Client_page)
        self.space.setGeometry(QtCore.QRect(20, 20, 881, 641))
        self.space.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.space.setObjectName("space")
        self.menu = QtWidgets.QWidget(parent=self.space)
        self.menu.setGeometry(QtCore.QRect(670, 470, 201, 161))
        self.menu.setObjectName("menu")
        self.plusMenu = QtWidgets.QPushButton(parent=self.menu)
        self.plusMenu.setGeometry(QtCore.QRect(150, 110, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plusMenu.sizePolicy().hasHeightForWidth())
        self.plusMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plusMenu.setFont(font)
        self.plusMenu.setStyleSheet("QPushButton\n"
"{\n"
"border-radius: 20px;\n"
"border: 1px solid rgb(153, 185, 255);\n"
"font: 36pt \"SimSun-ExtB\";\n"
"background-color : rgb(255,255,255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 36pt \"SimSun-ExtB\";\n"
"border: 1px solid rgb(222, 233, 255);\n"
"background-color: rgb(222, 233, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 36pt \"SimSun-ExtB\";\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.plusMenu.setIconSize(QtCore.QSize(27, 27))
        self.plusMenu.setCheckable(True)
        self.plusMenu.setObjectName("plusMenu")
        self.Menu = QtWidgets.QWidget(parent=self.menu)
        self.Menu.setGeometry(QtCore.QRect(20, 0, 131, 111))
        self.Menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Menu.setObjectName("Menu")
        self.fileUpload = QtWidgets.QPushButton(parent=self.Menu)
        self.fileUpload.setGeometry(QtCore.QRect(10, 26, 111, 23))
        self.fileUpload.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(222, 233, 255);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/file (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fileUpload.setIcon(icon)
        self.fileUpload.setCheckable(True)
        self.fileUpload.setObjectName("fileUpload")
        self.folderUpload = QtWidgets.QPushButton(parent=self.Menu)
        self.folderUpload.setGeometry(QtCore.QRect(10, 66, 111, 21))
        self.folderUpload.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(222, 233, 255);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/folder (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.folderUpload.setIcon(icon1)
        self.folderUpload.setCheckable(True)
        self.folderUpload.setObjectName("folderUpload")
        self.pushButton = QtWidgets.QPushButton(parent=self.space)
        self.pushButton.setGeometry(QtCore.QRect(760, 20, 101, 21))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(222, 233, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 10pt \"Nunito Medium\";\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/D:/download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(23, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Client_page)
        self.plusMenu.toggled['bool'].connect(self.Menu.setHidden) # type: ignore
        self.plusMenu.toggled['bool'].connect(self.Menu.hide) # type: ignore
        self.plusMenu.toggled['bool'].connect(self.Menu.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Client_page)

    def retranslateUi(self, Client_page):
        _translate = QtCore.QCoreApplication.translate
        Client_page.setWindowTitle(_translate("Client_page", "Form"))
        self.plusMenu.setText(_translate("Client_page", "+"))
        self.fileUpload.setText(_translate("Client_page", "File upload"))
        self.folderUpload.setText(_translate("Client_page", "Folder upload"))
        self.pushButton.setText(_translate("Client_page", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Client_page = QtWidgets.QWidget()
    ui = Ui_Client_page()
    ui.setupUi(Client_page)
    Client_page.show()
    sys.exit(app.exec())
