# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Server_page(object):
    def setupUi(self, Server_page):
        Server_page.setObjectName("Server_page")
        Server_page.resize(907, 705)
        Server_page.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        Server_page.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        Server_page.setAutoFillBackground(True)
        self.space = QtWidgets.QWidget(parent=Server_page)
        self.space.setGeometry(QtCore.QRect(10, 10, 881, 641))
        self.space.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.space.setObjectName("space")
        self.Symbol_column = QtWidgets.QWidget(parent=self.space)
        self.Symbol_column.setGeometry(QtCore.QRect(20, 20, 61, 601))
        self.Symbol_column.setStyleSheet("background-color: rgb(222, 233, 255);")
        self.Symbol_column.setObjectName("Symbol_column")
        self.clientsInfo_2 = QtWidgets.QPushButton(parent=self.Symbol_column)
        self.clientsInfo_2.setGeometry(QtCore.QRect(10, 70, 41, 23))
        self.clientsInfo_2.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.clientsInfo_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/information.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clientsInfo_2.setIcon(icon)
        self.clientsInfo_2.setCheckable(True)
        self.clientsInfo_2.setChecked(False)
        self.clientsInfo_2.setObjectName("clientsInfo_2")
        self.fileReceived_2 = QtWidgets.QPushButton(parent=self.Symbol_column)
        self.fileReceived_2.setGeometry(QtCore.QRect(10, 110, 41, 23))
        self.fileReceived_2.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.fileReceived_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/received.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fileReceived_2.setIcon(icon1)
        self.fileReceived_2.setCheckable(True)
        self.fileReceived_2.setChecked(False)
        self.fileReceived_2.setObjectName("fileReceived_2")
        self.Exit_2 = QtWidgets.QPushButton(parent=self.Symbol_column)
        self.Exit_2.setGeometry(QtCore.QRect(10, 570, 41, 23))
        self.Exit_2.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.Exit_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Exit_2.setIcon(icon2)
        self.Exit_2.setCheckable(True)
        self.Exit_2.setChecked(False)
        self.Exit_2.setObjectName("Exit_2")
        self.Info_column = QtWidgets.QWidget(parent=self.space)
        self.Info_column.setGeometry(QtCore.QRect(20, 20, 131, 601))
        self.Info_column.setStyleSheet("background-color: rgb(222, 233, 255);")
        self.Info_column.setObjectName("Info_column")
        self.fileReceived = QtWidgets.QPushButton(parent=self.Info_column)
        self.fileReceived.setGeometry(QtCore.QRect(5, 110, 121, 23))
        self.fileReceived.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.fileReceived.setIcon(icon1)
        self.fileReceived.setCheckable(True)
        self.fileReceived.setChecked(False)
        self.fileReceived.setObjectName("fileReceived")
        self.clientsInfo = QtWidgets.QPushButton(parent=self.Info_column)
        self.clientsInfo.setGeometry(QtCore.QRect(5, 70, 121, 23))
        self.clientsInfo.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.clientsInfo.setIcon(icon)
        self.clientsInfo.setCheckable(True)
        self.clientsInfo.setChecked(False)
        self.clientsInfo.setObjectName("clientsInfo")
        self.Exit = QtWidgets.QPushButton(parent=self.Info_column)
        self.Exit.setGeometry(QtCore.QRect(5, 570, 121, 23))
        self.Exit.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(0, 0, 0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border : 1px solid rgb(222, 233, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.Exit.setIcon(icon2)
        self.Exit.setCheckable(True)
        self.Exit.setChecked(False)
        self.Exit.setObjectName("Exit")
        self.notexpand = QtWidgets.QPushButton(parent=self.space)
        self.notexpand.setGeometry(QtCore.QRect(150, 20, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notexpand.sizePolicy().hasHeightForWidth())
        self.notexpand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.notexpand.setFont(font)
        self.notexpand.setStyleSheet("QPushButton\n"
"{\n"
"border: 1px solid rgb(222, 233, 255);\n"
"font: 13pt \"MS Sans Serif\";\n"
"background-color : rgb(255,255,255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 13pt \"MS Sans Serif\";\n"
"border: 1px solid rgb(222, 233, 255);\n"
"background-color: rgb(222, 233, 255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 13pt \"MS Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}")
        self.notexpand.setIconSize(QtCore.QSize(27, 27))
        self.notexpand.setCheckable(True)
        self.notexpand.setObjectName("notexpand")
        self.expand = QtWidgets.QPushButton(parent=self.space)
        self.expand.setGeometry(QtCore.QRect(80, 20, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expand.sizePolicy().hasHeightForWidth())
        self.expand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.expand.setFont(font)
        self.expand.setStyleSheet("QPushButton\n"
"{\n"
"border: 1px solid rgb(222, 233, 255);\n"
"font: 13pt \"MS Sans Serif\";\n"
"background-color : rgb(255,255,255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 13pt \"MS Sans Serif\";\n"
"border: 1px solid rgb(222, 233, 255);\n"
"background-color: rgb(222, 233, 255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 13pt \"MS Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius : 10px;\n"
"border-bottom-right-radius : 10px;\n"
"}")
        self.expand.setIconSize(QtCore.QSize(27, 27))
        self.expand.setCheckable(True)
        self.expand.setObjectName("expand")
        self.table_info = QtWidgets.QTableWidget(parent=self.space)
        self.table_info.setGeometry(QtCore.QRect(220, 100, 601, 431))
        self.table_info.setObjectName("table_info")
        self.table_info.setColumnCount(2)
        self.table_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_info.setHorizontalHeaderItem(1, item)
        self.expand.raise_()
        self.Symbol_column.raise_()
        self.Info_column.raise_()
        self.notexpand.raise_()
        self.table_info.raise_()

        self.retranslateUi(Server_page)
        self.clientsInfo.toggled['bool'].connect(self.clientsInfo_2.setChecked) # type: ignore
        self.fileReceived.toggled['bool'].connect(self.fileReceived_2.setChecked) # type: ignore
        self.Exit.toggled['bool'].connect(self.Exit_2.setChecked) # type: ignore
        self.Exit_2.clicked.connect(Server_page.close) # type: ignore
        self.Exit.clicked.connect(Server_page.close) # type: ignore
        self.notexpand.toggled['bool'].connect(self.Info_column.setHidden) # type: ignore
        self.notexpand.toggled['bool'].connect(self.expand.setVisible) # type: ignore
        self.expand.toggled['bool'].connect(self.notexpand.setHidden) # type: ignore
        self.notexpand.toggled['bool'].connect(self.notexpand.setHidden) # type: ignore
        self.expand.toggled['bool'].connect(self.expand.setHidden) # type: ignore
        self.expand.toggled['bool'].connect(self.Info_column.setVisible) # type: ignore
        self.expand.toggled['bool'].connect(self.notexpand.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Server_page)

    def retranslateUi(self, Server_page):
        _translate = QtCore.QCoreApplication.translate
        Server_page.setWindowTitle(_translate("Server_page", "Form"))
        self.fileReceived.setText(_translate("Server_page", "File received"))
        self.clientsInfo.setText(_translate("Server_page", "Clients\' Info"))
        self.Exit.setText(_translate("Server_page", "Stop"))
        self.notexpand.setText(_translate("Server_page", "<"))
        self.expand.setText(_translate("Server_page", ">"))
        item = self.table_info.horizontalHeaderItem(0)
        item.setText(_translate("Server_page", "Client Information"))
        item = self.table_info.horizontalHeaderItem(1)
        item.setText(_translate("Server_page", "IP Address"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Server_page = QtWidgets.QWidget()
    ui = Ui_Server_page()
    ui.setupUi(Server_page)
    Server_page.show()
    sys.exit(app.exec())
