# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 671)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(180, 100, 551, 511))
        self.widget.setObjectName("widget")
        self.input_username = QtWidgets.QTextBrowser(parent=self.widget)
        self.input_username.setGeometry(QtCore.QRect(116, 175, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito Light")
        font.setPointSize(10)
        self.input_username.setFont(font)
        self.input_username.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.input_username.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom : 2px solid rgb(1, 24, 156);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom: 1px;")
        self.input_username.setReadOnly(False)
        self.input_username.setObjectName("input_username")
        self.input_password = QtWidgets.QTextBrowser(parent=self.widget)
        self.input_password.setGeometry(QtCore.QRect(116, 235, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito Light")
        font.setPointSize(10)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom : 2px solid rgb(1, 24, 156);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom: 1px;")
        self.input_password.setReadOnly(False)
        self.input_password.setObjectName("input_password")
        self.dangnhap = QtWidgets.QLabel(parent=self.widget)
        self.dangnhap.setGeometry(QtCore.QRect(121, 45, 310, 131))
        font = QtGui.QFont()
        font.setFamily("Public Sans Black")
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.dangnhap.setFont(font)
        self.dangnhap.setStyleSheet("color : rgb(1, 24, 156)")
        self.dangnhap.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.dangnhap.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dangnhap.setObjectName("dangnhap")
        self.input_password_2 = QtWidgets.QTextBrowser(parent=self.widget)
        self.input_password_2.setGeometry(QtCore.QRect(116, 295, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito Light")
        font.setPointSize(10)
        self.input_password_2.setFont(font)
        self.input_password_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom : 2px solid rgb(1, 24, 156);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom: 1px;")
        self.input_password_2.setReadOnly(False)
        self.input_password_2.setObjectName("input_password_2")
        self.login = QtWidgets.QPushButton(parent=self.widget)
        self.login.setGeometry(QtCore.QRect(206, 385, 141, 31))
        self.login.setStyleSheet("QPushButton\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Nunito Medium\";\n"
"border-radius: 15px;\n"
"background-color: rgb(1, 24, 156);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"color: rgb(1, 24, 156);\n"
"font: 10pt \"Nunito Black\";\n"
"background-color: rgb(222, 233, 255);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"color: rgb(0,0,0);\n"
"font: 10pt \"Nunito Medium\";\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.login.setAutoDefault(False)
        self.login.setDefault(False)
        self.login.setObjectName("login")
        self.bg_2 = QtWidgets.QLabel(parent=self.widget)
        self.bg_2.setGeometry(QtCore.QRect(20, 15, 511, 481))
        self.bg_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_2.raise_()
        self.input_username.raise_()
        self.input_password.raise_()
        self.dangnhap.raise_()
        self.input_password_2.raise_()
        self.login.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_username.setPlaceholderText(_translate("Form", "Username"))
        self.input_password.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nunito Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.875pt;\"><br /></p></body></html>"))
        self.input_password.setPlaceholderText(_translate("Form", "Password"))
        self.dangnhap.setText(_translate("Form", "REGISTER"))
        self.input_password_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nunito Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.875pt;\"><br /></p></body></html>"))
        self.input_password_2.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.login.setText(_translate("Form", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
